spring:
  application:
    name: spring-cloud-demo-service-provider
  kafka:
    bootstrap-servers: localhost:9090
    consumer:
      value-deserializer: com.just1984.spring.cloud.demo.service.provider.serializer.ObjectDeserializer

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8090

just:
  web:
    mvc:
      globalExceptionHandler:
        enable: true