spring:
  application:
    name: spring-cloud-demo-service-provider
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      value-deserializer: com.just1984.spring.cloud.demo.service.provider.serializer.ObjectDeserializer
      group-id: GID_spring-cloud-demo-service-provider

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8090

just:
  web:
    mvc:
      globalExceptionHandler:
        enable: true