server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: spring-cloud-config-server-demo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yixiezi1994/spring-cloud-config-server-repository
          force-pull: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9999/eureka