server:
  port: 8070

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: spring-cloud-demo-service-consumer

spring-cloud-demo-service-provider:
  application:
    name: spring-cloud-demo-service-provider