server:
  port: 8070

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: spring-cloud-demo-service-consumer
  kafka:
    bootstrap-servers: localhost:9090
    producer:
      value-serializer: com.just1984.spring.cloud.demo.service.consumer.serializer.ObjectSerializer

feign:
  hystrix:
    enabled: false
